#Allows the plugin to start even if it may not be compatible with the current server version. This can lead to unexpected bugs and should only be used in a testing environment.
allow-unsupported-versions: false

#Filter specific settings.
filters:
  saturation: #Prevents players from seeing their saturation value.
    enabled: true
  worldseed: #Can make world seed cracking harder (but not impossible), but will slightly alter biome coloring.
    enabled: false
  enchantseed: #Can make enchantment seed cracking harder (but not impossible), but will slightly alter the galactic alphabet text in the enchanting table menu. (That text is useless anyways)
    enabled: true
  entitydata:
    enabled: true #This will toggle all entity data filters at once.
    airticks: #Hides the oxygen amount of other entities.
      enabled: false
    health: #Hides the health of other entities.
      enabled: true
    xp: #Hides the xp level of other players.
      enabled: true